Update worker process
Fixes https://github.com/MSFTOSSMgmt/WPSDSCLinux/issues/12

"Printf" debugging: (literally ;) ) revealed, that '/dsc' namespace is used. Obviously result was:

Error: The target namespace does not exist.
Namespace: /dsc

Updated namespace and got some results.

Still need to fix installation.